"""GENERATED by worlds/smb3/patch/gen_locks.py — DO NOT EDIT BY HAND.

SMB3 overworld path-lock topology: each gated level/toad-house panel that sits
behind one or more fortress locks -> the fortress clear(s) required to reach it.
Derived by flood-filling WorldNL.asm with fortress lock cells (FortressFX_*)
walled off. Used by Rules.py so level_access never routes progression behind an
unreachable panel. Regenerate with gen_locks.py."""

# base location name -> [required 'World N Fortress K - Cleared' events]
PANEL_REQUIRES_FORTRESS = {
    'World 6 Fortress 2 - Cleared': ['World 6 Fortress 1 - Cleared'],
    'World 6 Fortress 3 - Cleared': ['World 6 Fortress 1 - Cleared', 'World 6 Fortress 2 - Cleared'],
    'World 6 Level 6-10': ['World 6 Fortress 1 - Cleared', 'World 6 Fortress 2 - Cleared'],
    'World 6 Level 6-4': ['World 6 Fortress 1 - Cleared'],
    'World 6 Level 6-5': ['World 6 Fortress 1 - Cleared'],
    'World 6 Level 6-6': ['World 6 Fortress 1 - Cleared'],
    'World 6 Level 6-7': ['World 6 Fortress 1 - Cleared'],
    'World 6 Level 6-8': ['World 6 Fortress 1 - Cleared', 'World 6 Fortress 2 - Cleared'],
    'World 6 Level 6-9': ['World 6 Fortress 1 - Cleared', 'World 6 Fortress 2 - Cleared'],
}

